[metadata]
name = phydll
version = 0.0.0
author = A. Serhani
author_email = serhani@cerfacs.fr
description = Physics Deep Learning coupLer - Python DL interface
long_description = file: README.md
long_description_content_type = text/markdown
url = https://gitlab.com/cerfacs/phydll
project_urls =
    Homepage = https://gitlab.com/cerfacs/phydll
    Documentation = https://phydll.readthedocs.io/en/latest/
    Bug Tracker = https://gitlab.com/cerfacs/phydll/-/issues
classifiers =
    Programming Language :: Python :: 3
  #  License :: OSI Approved :: MIT License
  #  Operating System :: OS Independent
keyworlds =
    HPC
    Code coupling
    Massively parallel solvers
    Distributed neural networks

[options]
package_dir =
    = src/python
packages = find:
python_requires = >=3.6

install_requires =
    mpi4py
    numpy
    pyyaml
